## Routes de Alunos ##

adicionar_aluno:
   path: /onibus/{id_onibus}/aluno
   controller: App\Controller\AlunoController::insertAluno
   methods: POST

buscar_todos_alunos:
   path: /buscar/todos/alunos
   controller: App\Controller\AlunoController::buscarTodosAlunos
   methods: GET

atualizar_aluno:
   path: /aluno/{id}
   controller: App\Controller\AlunoController::updateAluno
   methods: PUT

deletar_aluno:
   path: /aluno/{id}
   controller: App\Controller\AlunoController::deleteAluno
   methods: DELETE

buscar_um_aluno:
   path: /busca/aluno/{id}
   controller: App\Controller\AlunoController::buscarAluno
   methods: GET

## Routes de Onibus ##

adicionar_onibus:
   path: /onibus
   controller: App\Controller\OnibusController::insertOnibus
   methods: POST

buscar_todos_onibus:
   path: /buscar/todos/onibus
   controller: App\Controller\OnibusController::buscarTodosOnibus
   methods: GET

atualizar_onibus:
   path: /onibus/{id}
   controller: App\Controller\OnibusController::updateOnibus
   methods: PUT

deletar_onibus:
   path: /onibus/{id}
   controller: App\Controller\OnibusController::deleteOnibus
   methods: DELETE

buscar_um_onibus:
   path: /busca/onibus/{id}
   controller: App\Controller\OnibusController::buscarOnibus
   methods: GET

## Routes de Rotas ##

adicionar_rota:
   path: /rota
   controller: App\Controller\RotaController::insertRota
   methods: POST

buscar_todas_rotas:
   path: /buscar/todas/rotas
   controller: App\Controller\RotaController::buscarTodasRotas
   methods: GET

atualizar_rota:
   path: /rota/{id}
   controller: App\Controller\RotaController::updateRota
   methods: PUT

deletar_rota:
   path: /rota/{id}
   controller: App\Controller\RotaController::deleteRota
   methods: DELETE

buscar_uma_rota:
   path: /busca/rota/{id}
   controller: App\Controller\RotaController::buscarRota
   methods: GET

## Routes de Pontos ##

adicionar_ponto:
   path: /ponto
   controller: App\Controller\PontoController::insertPonto
   methods: POST

buscar_todos_pontos:
   path: /buscar/todos/pontos
   controller: App\Controller\PontoController::buscarTodosPontos
   methods: GET

atualizar_ponto:
   path: /ponto/{id}
   controller: App\Controller\PontoController::updatePonto
   methods: PUT

deletar_ponto:
   path: /ponto/{id}
   controller: App\Controller\PontoController::deletePonto
   methods: DELETE

buscar_um_pontp:
   path: /busca/ponto/{id}
   controller: App\Controller\PontoController::buscarPonto
   methods: GET

## Routes Rota Ponto ##

juntar_rota_onibus:
   path: /rota/{id_rota}/onibus/{id_onibus}
   controller: App\Controller\RotaController::juncaoRotaOnibus
   methods: POST