## Base WEB ##

base_html:
   path: /
   controller: App\Controller\BustecAdm\HomeRender::buscaTotais
   methods: GET


## Routes de Alunos ##

   ## API ##
adicionar_aluno:
   path: /onibus/{id_onibus}/aluno
   controller: App\Controller\BustecApi\AlunoController::insertAluno
   methods: POST

buscar_todos_alunos:
   path: /buscar/todos/alunos
   controller: App\Controller\BustecApi\AlunoController::buscarTodosAlunos
   methods: GET

atualizar_aluno:
   path: onibus/{id_onibus}/aluno/{id}
   controller: App\Controller\BustecApi\AlunoController::updateAluno
   methods: PUT

deletar_aluno:
   path: /aluno/{id}
   controller: App\Controller\BustecApi\AlunoController::deleteAluno
   methods: DELETE

buscar_um_aluno:
   path: /busca/aluno/{id}
   controller: App\Controller\BustecApi\AlunoController::buscarAluno
   methods: GET

   ## WEB ##

adicionar_aluno_html:
    path: /aluno/cadastro
    controller: App\Controller\BustecAdm\AlunoRender::cadastroAluno
    methods: GET

atualizar_aluno_html:
    path: /aluno/atualizar/{id_aluno}
    controller: App\Controller\BustecAdm\AlunoRender::atualizarAluno
    methods: GET

listar_aluno_html:
    path: /aluno/listar-todos
    controller: App\Controller\BustecAdm\AlunoRender::listarAlunos
    methods: GET

## Routes de Onibus ##

   ## API ##
adicionar_onibus:
   path: /onibus
   controller: App\Controller\BustecApi\OnibusController::insertOnibus
   methods: POST

buscar_todos_onibus:
   path: /buscar/todos/onibus
   controller: App\Controller\BustecApi\OnibusController::buscarTodosOnibus
   methods: GET

atualizar_onibus:
   path: /onibus/{id}
   controller: App\Controller\BustecApi\OnibusController::updateOnibus
   methods: PUT

deletar_onibus:
   path: /onibus/{id}
   controller: App\Controller\BustecApi\OnibusController::deleteOnibus
   methods: DELETE

buscar_um_onibus:
   path: /busca/onibus/{id}
   controller: App\Controller\BustecApi\OnibusController::buscarOnibus
   methods: GET

   ## WEB ##

adicionar_onibus_html:
   path: /onibus/cadastro
   controller: App\Controller\BustecAdm\OnibusRender::cadastroOnibus
   methods: GET

atualizar_onibus_html:
   path: /onibus/atualizar/{id_onibus}
   controller: App\Controller\BustecAdm\OnibusRender::atualizarOnibus
   methods: GET

listar_onibus_html:
   path: /onibus/listar-todos
   controller: App\Controller\BustecAdm\OnibusRender::listarOnibus
   methods: GET

## Routes de Rotas ##

   ## API ##
adicionar_rota:
   path: /rota
   controller: App\Controller\BustecApi\RotaController::insertRota
   methods: POST

buscar_todas_rotas:
   path: /buscar/todas/rotas
   controller: App\Controller\BustecApi\RotaController::buscarTodasRotas
   methods: GET

atualizar_rota:
   path: /rota/{id}
   controller: App\Controller\BustecApi\RotaController::updateRota
   methods: PUT

deletar_rota:
   path: /rota/{id}
   controller: App\Controller\BustecApi\RotaController::deleteRota
   methods: DELETE

buscar_uma_rota:
   path: /busca/rota/{id}
   controller: App\Controller\BustecApi\RotaController::buscarRota
   methods: GET


vinculos_rota_html:
   path: /rota/vinculos/{id_rota}
   controller: App\Controller\BustecAdm\RotasRender::vinculosOnibus
   methods: GET

   ## WEB ##

adicionar_rota_html:
   path: /rota/cadastro
   controller: App\Controller\BustecAdm\RotasRender::cadastroRotas
   methods: GET

atualizar_rota_html:
   path: /rota/atualizar/{id_rotas}
   controller: App\Controller\BustecAdm\RotasRender::atualizarRotas
   methods: GET

listar_rota_html:
   path: /rota/listar-todos
   controller: App\Controller\BustecAdm\RotasRender::listarRotas
   methods: GET

## Routes de Pontos ##

   ## API ##

adicionar_ponto:
   path: /ponto
   controller: App\Controller\BustecApi\PontoController::insertPonto
   methods: POST

buscar_todos_pontos:
   path: /buscar/todos/pontos
   controller: App\Controller\BustecApi\PontoController::buscarTodosPontos
   methods: GET

atualizar_ponto:
   path: /ponto/{id}
   controller: App\Controller\BustecApi\PontoController::updatePonto
   methods: PUT

deletar_ponto:
   path: /ponto/{id}
   controller: App\Controller\BustecApi\PontoController::deletePonto
   methods: DELETE

buscar_um_pontp:
   path: /busca/ponto/{id}
   controller: App\Controller\BustecApi\PontoController::buscarPonto
   methods: GET

   ## WEB ##

adicionar_ponto_html:
   path: /ponto/cadastro
   controller: App\Controller\BustecAdm\PontoRender::cadastroPonto
   methods: GET

atualizar_ponto_html:
   path: /ponto/atualizar/{id_rotas}
   controller: App\Controller\BustecAdm\PontoRender::atualizarPonto
   methods: GET

listar_ponto_html:
   path: /ponto/listar-todos
   controller: App\Controller\BustecAdm\PontoRender::listarPonto
   methods: GET

## Routes Rota Onibus ##

   ## API ##

juntar_rota_onibus:
   path: /rota/{id_rota}/onibus/{id_onibus}
   controller: App\Controller\BustecApi\RotaController::juncaoRotaOnibus
   methods: POST

deletar_rota_onibus:
   path: /rota/onibus/{id}
   controller: App\Controller\BustecApi\RotaController::excluiJuncaoRotaOnibus
   methods: DELETE

atualizar_rota_onibus:
   path: /vinculo/{id}/rota/{id_rota}/onibus/{id_onibus}
   controller: App\Controller\BustecApi\RotaController::updateRotaOnibus
   methods: PUT

   ## WEB ##

vincular_rota_onibus_html:
   path: /rota/vicular/rota-onibus
   controller: App\Controller\BustecAdm\RotasRender::vinculaRotaOnibus
   methods: GET

atualizar_rota_onibus_html:
   path: /vinculo/{id}/rota/onibus
   controller: App\Controller\BustecAdm\RotasRender::atualizarRotaOnibus
   methods: GET

## Routes Rota Ponto ##

 ## API ##

juntar_rota_ponto:
   path: /rota/{id_rota}/ponto/{id_ponto}
   controller: App\Controller\BustecApi\RotaController::juncaoRotaPonto
   methods: POST

deletar_rota_ponto:
   path: /rota/ponto/{id}
   controller: App\Controller\BustecApi\RotaController::excluiJuncaoRotaPonto
   methods: DELETE

atualizar_rota_ponto:
   path: /vinculo/{id}/rota/{id_rota}/ponto/{id_ponto}
   controller: App\Controller\BustecApi\RotaController::updateRotaPonto
   methods: PUT

   ## WEB ##

vincular_rota_ponto_html:
   path: /rota/vicular/rota-ponto
   controller: App\Controller\BustecAdm\RotasRender::vinculaRotaPonto
   methods: GET

atualizar_rota_ponto_html:
   path: /vinculo/{id}/rota/ponto
   controller: App\Controller\BustecAdm\RotasRender::atualizarRotaPonto
   methods: GET

## Routes Login ##

   ## API ##

login_api:
   path: /login
   controller: App\Controller\BustecApi\LoginController::index
   methods: POST

criar_login_api:
   path: /cadastrar/login
   controller: App\Controller\BustecApi\UserController::cadastrarUsuario
   methods: POST

   ## WEB ##

login_web:
   path: /bustec/login
   controller: App\Controller\BustecAdm\LoginRender::login
   methods: GET

