## Routes de Alunos ##

adicionar_aluno:
   path: /onibus/{id_onibus}/aluno
   controller: App\Controller\AlunoController::insertAluno
   methods: POST

buscar_todos_alunos:
   path: /buscar/todos/alunos
   controller: App\Controller\AlunoController::buscarTodosAlunos
   methods: GET

atualizar_aluno:
   path: /aluno/{id}
   controller: App\Controller\AlunoController::updateAluno
   methods: PUT

deletar_aluno:
   path: /aluno/{id}
   controller: App\Controller\AlunoController::deleteAluno
   methods: DELETE

buscar_um_aluno:
   path: /busca/aluno/{id}
   controller: App\Controller\AlunoController::buscarAluno
   methods: GET

## Routes de Onibus ##

adicionar_onibus:
   path: /onibus
   controller: App\Controller\OnibusController::insertOnibus
   methods: POST

buscar_todos_onibus:
   path: /buscar/todos/onibus
   controller: App\Controller\OnibusController::buscarTodosOnibus
   methods: GET

atualizar_onibus:
   path: /onibus/{id}
   controller: App\Controller\OnibusController::updateOnibus
   methods: PUT

deletar_onibus:
   path: /onibus/{id}
   controller: App\Controller\OnibusController::deleteOnibus
   methods: DELETE

buscar_um_onibus:
   path: /busca/onibus/{id}
   controller: App\Controller\OnibusController::buscarOnibus
   methods: GET